/**
 * \file    Cpu1_Main.c
 * \brief   CPU1 idle entry point for the TC275 custom bootloader.
 *
 *          The bootloader runs entirely on CPU0. CPU1 is not used and remains
 *          in this idle loop for the bootloader's entire lifetime.
 *
 *          CPU1 watchdog is disabled here to prevent a CPU reset caused by
 *          the watchdog expiring while CPU1 is idle. The CPU sync event
 *          (IfxCpu_emitEvent / IfxCpu_waitEvent) is left commented out;
 *          the bootloader does not require inter-CPU synchronization.
 *
 * \note    When the application starts, it is responsible for releasing
 *          CPU1 from this idle loop via its own startup mechanism if needed.
 */

/**********************************************************************************************************************
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the Software, and to permit
 * third-parties to whom the Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this
 * restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part,
 * and all derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,
 * WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

/**
 * \brief   CPU1 entry function — idle loop.
 *
 *          Disables the CPU1 watchdog to prevent spurious resets, then
 *          enters an infinite idle loop. No bootloader logic runs on CPU1.
 */
void core1_main(void)
{
    /* Disable CPU1 watchdog — not serviced in the bootloader idle loop. */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

    while (1)
    {
        /* Idle — CPU1 is unused by the bootloader. */
    }
}
